version: "3.8"

services:
  db:
    image: postgres
    container_name: postgres_db_synrgy
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdatasynrgy:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_car
      - POSTGRES_USER=dwiki
      - POSTGRES_PASSWORD=dwiki123
      - TZ=UTC
      - PGTZ =UTC
volumes:
  pgdatasynrgy:
