# fly.toml app configuration file generated for rent-car-api on 2023-12-15T10:01:56+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rent-car-api"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
